### ISSUE TITLE
Multiple XPath Selection/Copy

### ISSUE THREAD

**Issue by BrutalSimplicity** [rosshadden/sublime-xpath#10]
Sorry, I've been thinking about this for a while, but thought it would be better to make a separate issue. It would also be cool if you could take advantage of sublime multi-selection and copy a range of XPaths, so you don't have to go to each individual element. I would imagine this would utilize the code you've already written to make a list, and then remove any duplicate entries and return them to the user on multiple lines. What do you think?

**Comment by keith-hall** [comment]
Hi, thanks for your suggestion. This functionality already exists, and there is a preference `copy_unique_path_only` that can be set to control whether duplicate entries should be removed or not. It defaults to true :+1:

**Comment by BrutalSimplicity** [comment]
Oh wow, you're right! Nice, that's real slick. Thanks.
