### ISSUE TITLE
Searching for xml on package control doesn't show this plugin

### ISSUE THREAD

**Issue by keith-hall** [rosshadden/sublime-xpath#11]
Hi,

I've noticed that when [searching on package control for 'xml'](https://packagecontrol.io/search/xml), xpath isn't one of the results.  It's possible that this plugin therefore isn't getting as much attention as it could, and I am sure more people could benefit from it.  I guess this is fixable by updating the package control repository to include xml as a label. :)

Thanks

**Comment by rosshadden** [comment]
Thanks for the suggestion.  I'll do this when I get a few minutes.

**Comment by rosshadden** [comment]
I should have done this a long time ago.  Somehow I forgot, despite the TODO entry and the pinned github email.

Oh well.  Closed by https://github.com/wbond/package_control_channel/pull/5205

**Comment by keith-hall** [comment]
Thanks Ross :)

**Comment by rosshadden** [comment]
Interesting... check out the post-merge comment on https://github.com/wbond/package_control_channel/pull/5205.

**Comment by keith-hall** [comment]
That is indeed interesting... makes me wonder what the purpose of tags/labels are in package control... oh well, never mind - we will need to update the description anyway once we get my xpath query changes in - I will raise a separate issue for that at the appropriate time :) thanks again!
