### ISSUE TITLE
It is unclear how to install... Don't see this sublime-xpath available on Package Control

### ISSUE THREAD

**Issue by rcranney** [rosshadden/sublime-xpath#2]
Hi, 

I am a relatively new Sublime Text user and when I downloaded the zip file, it was unclear how to install... Could you please provide some install directions? 

Updated: so, apparently, Package Control has functionality that allows you to Add a Repository.  So, I pointed it to this Github project.  I was then able to install Sublime-xpath using Package Control.  .  

Unfortunately, when I ran XPATH from Command Palette, it doesn't seem to copy the xpath to memory.  I also noticed the option on a right click menu to XPATH: Copy path to clipboard.  After selecting this and then pasting (CTL+V) it does not paste the XPATH, but text that was already in memory.  

Any suggestions would be appreciated.

**Comment by rosshadden** [comment]
You're right; it doesn't work for me either.

I switched to `vim` a couple of years ago and have only been updating this when people find bugs.  I'll see if I can figure out what's wrong and fix it when I get a chance.

I never published this to package control.  I didn't know about that "Add a Repository" feature, that is really cool and is a good way to install this plugin.  Once I fix the above issue, I guess I'll publish it to the official package repo to make it easier on people.

Thanks!

**Comment by rosshadden** [comment]
I fixed the issue you brought up, and also [submitted this plugin to Package Control](https://github.com/wbond/package_control_channel/pull/4103).

Thanks!
