### ISSUE TITLE
Stalled at "XML being parsed..."

### ISSUE THREAD

**Issue by thug-els** [rosshadden/sublime-xpath#22]
Opening any XML file (including the exmple_xml_ns.xml file here), just shows "XML being parsed..." in the status bar, and none of the commands from Command Palette work.

Using ST3 build 3103 on OS X (El Capitan) & v2.4.0 of this package.

**Comment by keith-hall** [comment]
Hi, sorry to hear that - please can you check the Sublime Text Console for errors and post them here? :)

`View` menu -> `Show Console`

**Comment by ccsplit** [comment]
I am having a similar issue. The `console` shows the following on mine each time:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "xpath in /Users/cshay/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 409, in on_activated_async
  File "xpath in /Users/cshay/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 261, in updateStatusToCurrentXPathIfSGML
KeyError: 19
```

**Comment by thug-els** [comment]
error seems to be "lxml.etree.ParserError: Unicode parsing is not supported on this platform"

Full message:

> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 333, in on_activated_async
>     callback.on_activated_async(v)
>   File "xpath in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 409, in on_activated_async
>   File "xpath in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 255, in updateStatusToCurrentXPathIfSGML
>   File "xpath in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 104, in ensureTreeCacheIsCurrent
>   File "xpath in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 68, in buildTreesForView
>   File "xpath in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 80, in buildTreeForViewRegion
>   File "lxml_parser in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 193, in lxml_etree_parse_xml_string_with_location
>   File "lxml_parser in /Users/thug-els/Library/Application Support/Sublime Text 3/Installed Packages/xpath.sublime-package", line 80, in feed
>   File "parser.pxi", line 1201, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:102246)
>   File "parser.pxi", line 1236, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:101171)
> lxml.etree.ParserError: Unicode parsing is not supported on this platform

**Comment by keith-hall** [comment]
> lxml.etree.ParserError: Unicode parsing is not supported on this platform

wow, that doesn't sound good! seems like a major limitation of `lxml`... [This thread](https://groups.google.com/forum/#!topic/beautifulsoup/68CG0m-6tv8) seems to be related and might help us find a fix, in particular this bit interests me:

> Meanwhile, I managed to solve my particular problem in another way, by telling the lxml setup code to download,build and statically link libxml2 instead of relying on the MacOS supplied libs:
>
> STATIC_DEPS=true pip install lxml

 So maybe we can resolve this by recompiling the `lxml` dependency...

Which CPU variant of OS X are you two using? x64 or x32?

**Comment by thug-els** [comment]
Keith:

Using x64.

**Comment by ccsplit** [comment]
I am using x86_64, and I also can get the same error as @thug-els the first time I set syntax to xml, which the index error appears to occur after this when looking up the view. However, using `STATIC_DEPS=true pip install lxml` doesn't appear to work for me as the lxml module installed within ST3 is from  [sublime-lxml](https://github.com/eerohele/sublime-lxml) and overwriting the `st3_osx_x64` version still doesn't appear to work for other reasons. Although that could be differences in the way it was built.

**Comment by keith-hall** [comment]
thanks for the prompt responses @thug-els and @ccsplit. Unfortunately I have no access to a Mac, which makes it tricky for me to investigate this. I don't want to pass the buck, and wish I could do more, but maybe we will have better luck creating an issue on the [sublime-lxml](https://github.com/eerohele/sublime-lxml) repo, and linking to this one so that the maintainer of the ST3 lxml dependency has all this info to work with. I am happy to do this when I get chance, but feel free to beat me to it ;)

**Comment by rosshadden** [comment]
Yeah it seems to work fine in Arch Linux.  I don't have access to a Mac to test, either.

**Comment by keith-hall** [comment]
To help remove any complications arising from this package, and for a perhaps simpler reproducable test case, can you execute the following in the Sublime console and post the results please @ccsplit ?

    from lxml import etree
    etree.get_default_parser().feed('<xml><node>text</node></xml>')
    etree.tostring(etree.get_default_parser().close()) 

I suspect you will get the error on the the second line and therefore not need to type the third.

**Comment by ccsplit** [comment]
@keith-hall as expected the error does occur:
```
>>> from lxml import etree
>>> etree.get_default_parser().feed('<xml><node>text</node></xml>')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "parser.pxi", line 1201, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:102246)
  File "parser.pxi", line 1236, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:101171)
lxml.etree.ParserError: Unicode parsing is not supported on this platform
```

**Comment by rosshadden** [comment]
@thug-els @ccsplit Try now, after updating `sublime-xpath` to the latest version (currently `v2.4.1`).

**Comment by thug-els** [comment]
@rosshadden , Package Control is showing 2.4.0 as latest version. Is there another way to get to 2.4.1 (or am I perhaps using Package Control wrong)?

**Comment by rosshadden** [comment]
Yeah it must be cached.

**Comment by thug-els** [comment]
Package Control site just updated. Got it! 2.4.1 confirmed working on Mac! Thanks @rosshadden and @keith-hall for the very quick fix!

**Comment by ccsplit** [comment]
@rosshadden It worked for me also, thanks @rosshadden  and @keith-hall.

@thug-els fyi, if you want to update the changes in the future you can use ST3's [customization/overriding feature](http://docs.sublimetext.info/en/latest/extensibility/packages.html#customizing-or-overriding-packages).

**Comment by keith-hall** [comment]
super, glad this resolved the issue - thanks for reporting it :) 

for future reference, you can see on the Package Control website when a repo was "last seen" - typically Package Control checks for new versions about once an hour I think, so worst case scenario, you would have to wait 59 minutes and 59 seconds to get a new version automatically ;)
