### ISSUE TITLE
Spams status bar with error message

### ISSUE THREAD

**Issue by golaod** [rosshadden/sublime-xpath#24]
Parsing xml is fired in every file type, so you keep seeing 'Xpath - error parsing XML......' (message is longer ).

Is there a way to parse file content only if its type is xml?

**Comment by keith-hall** [comment]
Interesting, it should only be triggering on XML and HTML. Does it even happen when you create a new, empty tab?

**Comment by keith-hall** [comment]
I guess it could trigger on other types that include HTML or XML, so on source code with XML comments for example. Can you share a document on which it is happening please? It may be that we will need to add a new setting for file types to include and/or exclude.

**Comment by golaod** [comment]
I can even open empty *.php file and it parses it content, which of course is not valid XML file

**Comment by keith-hall** [comment]
ah makes sense - it sees it as html. I will add a setting and make it ignore php by default. Thanks for repprting

**Comment by keith-hall** [comment]
I have made the fix as discussed and opened a PR for it. After it has been reviewed and merged, it will take about an hour for Package Control to notice the updated version.

**Comment by golaod** [comment]
Never expected such fast response. Thanks :)
