### ISSUE TITLE
As a potential user I would like to install manually without using package control

### ISSUE THREAD

**Issue by wheresjim** [rosshadden/sublime-xpath#31]
My company makes it difficult to use package control directly because of SSL proxying.  I would like to be able to install the package manually if possible.

Could you provide instructions on how to do so?

**Comment by rosshadden** [comment]
Just like you do any other Sublime Text package.  Clone it into the Sublime's packages folder.

**Comment by keith-hall** [comment]
There's a bit more to it than that - you'll also need to clone https://github.com/eerohele/sublime-lxml as well. If you don't/can't use git, then an easy way to do this is to go to the repo on GitHub's website and click the download zip button.
To get to ST's packages folder, you can go to the Tools menu in ST -> Browse Packages.

The folder structure you want is something like this (the names and nesting are important, if you are downloading the zip, you may need to make some manual changes):

```
Packages
|- lxml
|  |- st3_linux_x64
|  |- st3_osx_x64
|  |- st3_windows_x64
|- xpath
   |- messages
```
(forgive my crude diagram, I'm on mobile atm)
