### ISSUE TITLE
Does not show up in the Package Control Install list

### ISSUE THREAD

**Issue by bmix** [rosshadden/sublime-xpath#35]
As the title says it, I do not get this addon as an entry in the "Package Control: Install" list. So I can not install it via Package Control.

**Comment by keith-hall** [comment]
[it shows up on Package Control's website](https://packagecontrol.io/packages/xpath), so should also show up in the Install list in ST. Maybe it is already installed or something? [There are no restrictions on ST version or OS.](https://github.com/wbond/package_control_channel/blob/dfe202bb0f93e1d6cfb15bd919710b2f588684be/repository/x.json#L149-L163)

**Comment by bmix** [comment]
Sorry, totally my fault. I had installed it (long time ago), but disabled it.
