### ISSUE TITLE
processing-instruction() is missing

### ISSUE THREAD

**Issue by anthonyBertrant** [rosshadden/sublime-xpath#37]
Hi guy ! First: your plug-in is AMAZING and you've done an AMAZING work ! I use your plug-in for my studies in France and I love it ! But I think I found an issue with the XPath: Query Document function. 
When I want to launch processing-instruction(), the plug-in doesn't find it, or , it's a function of XPath and it can't find this instruction. Can you help me ?

Thanks in advance and sorry for my VERY bad english

;-)

**Comment by keith-hall** [comment]
Hi (Bonjour), thanks for the feedback :)

I can confirm that this seems to be a bug - with a simple XML document like:

```xml
<test>
    <?helloworld ?>
</test>
```

using `XPath: Query Document` to query for `//node()` doesn't include the processing instruction `helloworld` in the results list.

I don't have time to investigate properly right now, but a quick fix to get it to appear would be to add the following method to [`lxml_parser.py`'s `LocationAwareTreeBuilder` class](https://github.com/rosshadden/sublime-xpath/blob/1d9bdd3f375f7074e3fbf5f09e2fccf2725edb85/lxml_parser.py#L175):

```python
    def pi(self, target, data, location=None):
        self._appendNode(etree.PI(target, data))
```

(open it using https://packagecontrol.io/packages/PackageResourceViewer and save the change, then restart ST)
Then the output will be like this:

![image](https://user-images.githubusercontent.com/11882719/35338413-9089543a-0126-11e8-88ab-7f43a813d666.png)

I'm not yet sure how involved it will be to fix this properly - i.e. preserving location information - but I'll see what I can do when I get some free time.
